import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqs = [
  {
    question: "Does it support multiple ad accounts?",
    answer: "Yes, our AI agent can manage multiple Google Ads accounts simultaneously. You can connect unlimited accounts and manage them from a single dashboard with account-specific optimization strategies."
  },
  {
    question: "Can I customize ad copy generated by AI?",
    answer: "Absolutely! While our AI generates high-converting ad copy automatically, you have full control to edit, customize, or completely rewrite any generated content before campaigns go live."
  },
  {
    question: "Is this safe to use with my existing campaigns?",
    answer: "Yes, our AI agent is designed to work safely with existing campaigns. It makes gradual optimizations and always requires your approval for major changes. You can also set spending limits and pause automation at any time."
  },
  {
    question: "How does the AI learn about my business?",
    answer: "The AI analyzes your website, existing campaigns, industry data, and competitor intelligence to understand your business context. You can also provide additional context during setup to improve targeting accuracy."
  },
  {
    question: "What's included in the free trial?",
    answer: "The free trial includes full access to all AI agent features for 14 days, including campaign creation, optimization, and analytics. No credit card required to start, and you can upgrade anytime."
  }
];

export const AIAgentGoogleAdsFAQ = () => {
  return (
    <section className="py-16 md:py-20">
      <div className="container mx-auto px-4">
        <div className="text-center space-y-4 mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know about using AI for Google Ads automation.
          </p>
        </div>
        
        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left text-lg font-semibold">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};