
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <main className="py-20">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="mb-12">
              <h1 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-6">
                Privacy Policy
              </h1>
              <p className="text-lg text-gray-600">
                Effective Date: March 25, 2024
              </p>
            </div>

            <div className="prose prose-lg max-w-none text-gray-700">
              {/* Introduction */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Introduction</h2>
                <p className="mb-4">
                  AdSpyder ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by AdSpyder.
                </p>
                <p className="mb-4">
                  This Privacy Policy applies to our website and its associated subdomains (collectively, our "Service") alongside our application, AdSpyder. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                </p>
              </section>

              {/* Definitions */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Definitions and Key Terms</h2>
                <p className="mb-6">
                  To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:
                </p>
                <div className="space-y-4">
                  <div>
                    <strong>Cookie:</strong> Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.
                  </div>
                  <div>
                    <strong>Company:</strong> When this policy mentions "Company," "we," "us," or "our," it refers to GSTECH TECHNOLOGY PRIVATE LIMITED, 810, 4th FLOOR, 27th MAIN, 1ST SECTOR, HSR LAYOUT, Bengaluru, Bengaluru Urban, Karnataka, 560102 that is responsible for your information under this Privacy Policy.
                  </div>
                  <div>
                    <strong>Country:</strong> Where AdSpyder or the owners/founders of AdSpyder are based, in this case is India.
                  </div>
                  <div>
                    <strong>Customer:</strong> Refers to the company, organization or person that signs up to use the AdSpyder Service to manage the relationships with your consumers or service users.
                  </div>
                  <div>
                    <strong>Device:</strong> Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit AdSpyder and use the services.
                  </div>
                  <div>
                    <strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
                  </div>
                  <div>
                    <strong>Personnel:</strong> Refers to those individuals who are employed by AdSpyder or are under contract to perform a service on behalf of one of the parties.
                  </div>
                  <div>
                    <strong>Personal Data:</strong> Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                  </div>
                  <div>
                    <strong>Service:</strong> Refers to the service provided by AdSpyder as described in the relative terms (if available) and on this platform.
                  </div>
                  <div>
                    <strong>Third-party service:</strong> Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                  </div>
                  <div>
                    <strong>Website:</strong> AdSpyder's site, which can be accessed via this URL: <a href="https://adspyder.io/" className="text-orange-600 hover:text-orange-700">https://adspyder.io/</a>
                  </div>
                  <div>
                    <strong>You:</strong> A person or entity that is registered with AdSpyder to use the Services.
                  </div>
                </div>
              </section>

              {/* Information We Collect */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Information We Collect</h2>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Information Automatically Collected</h3>
                <p className="mb-4">
                  There is some information like your Internet Protocol (IP) address and/or browser and device characteristics that is collected automatically when you visit our platform. This information may be used to connect your computer to the Internet. Other information collected automatically could include login, email address, password, computer and connection information such as browser plug-in types and versions and time zone setting, operating systems and platforms, purchase history, the full Uniform Resource Locator (URL) clickstream to, through and from our Website that may include date and time; cookie number; parts of the site you viewed or searched for; and the phone number you used to call our Customer Services.
                </p>
                <p className="mb-4">
                  We may also use browser data such as cookies, Flash cookies (also known as Flash Local Shared Objects) or similar data on certain parts of our Website for fraud prevention and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect session information including page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Personnel Information</h3>
                <p className="mb-4">
                  If you are an AdSpyder worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.
                </p>
              </section>

              {/* How We Use Your Information */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">How We Use Your Information</h2>
                <p className="mb-4">
                  We automatically collect certain information when you visit, use or navigate the platform. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our platform and other technical information. This information is primarily needed to maintain the security and operation of our platform, and for our internal analytics and reporting purposes.
                </p>
                <p className="mb-4">
                  You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.
                </p>
              </section>

              {/* Cookies and Tracking Technologies */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Cookies and Tracking Technologies</h2>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Cookies</h3>
                <p className="mb-4">
                  AdSpyder uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.
                </p>
                <p className="mb-4">
                  Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Cookies for Advertising</h3>
                <p className="mb-4">
                  These cookies collect information over time about your online activity on the website and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it's really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Facebook Pixel</h3>
                <p className="mb-4">
                  Facebook pixel is an analytics tool that allows you to measure the effectiveness of your advertising by understanding the actions people take on your website. You can use the pixel to make sure your ads are shown to the right people. Facebook pixel may collect information from your device when you use the service. Facebook pixel collects information that is held in accordance with its Privacy Policy.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Blocking and Disabling Cookies</h3>
                <p className="mb-4">
                  Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
                </p>
              </section>

              {/* Your Rights */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Your Rights</h2>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Your Consent</h3>
                <p className="mb-4">
                  We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
                </p>
                <p className="mb-4">
                  By using AdSpyder or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Acquiring User Consent</h3>
                <p className="mb-4">
                  Before any of your data is shared with third-party tools, we ensure to acquire your explicit consent. Upon your first use of our application, and at any time when significant changes are made to our data-sharing practices, we present you with a clear and concise consent form. This form details the nature of the data being shared, the purpose of the sharing, and the identity of the third-party recipients. You have the full right to opt-in or opt-out of this data sharing. Your decision can be altered at any time through the settings menu, ensuring you have continuous control over your personal information. We assure you that no sharing will occur without your explicit and informed consent, safeguarding your privacy at every step.
                </p>
              </section>

              {/* GDPR and CCPA Compliance */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">GDPR and CCPA Compliance</h2>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">General Data Protection Regulation (GDPR)</h3>
                <p className="mb-4">
                  We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why this data is collected, and how we maintain this data under protection from being replicated or used in the wrong way.
                </p>
                
                <h4 className="text-xl font-semibold text-gray-700 mb-3">What is GDPR?</h4>
                <p className="mb-4">
                  GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and enhances the control the EU residents have over their personal data. The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our customers' data is important irrespective of where they are located, which is why we have implemented GDPR controls as our baseline standard for all our operations worldwide.
                </p>
                
                <h4 className="text-xl font-semibold text-gray-700 mb-3">What is Personal Data?</h4>
                <p className="mb-4">
                  Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person's name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical addresses, sexual orientation, and ethnicity.
                </p>
                
                <h4 className="text-xl font-semibold text-gray-700 mb-3">Data Protection Principles</h4>
                <ul className="list-disc list-inside mb-4 space-y-2">
                  <li>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</li>
                  <li>Personal data should only be collected to fulfill a specific purpose and it should only be used for that purpose.</li>
                  <li>Organizations must specify why they need the personal data when they collect it.</li>
                  <li>Personal data should be held no longer than necessary to fulfill its purpose.</li>
                  <li>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</li>
                </ul>
                
                <h4 className="text-xl font-semibold text-gray-700 mb-3">Individual Data Subject's Rights</h4>
                <p className="mb-4">
                  We are committed to helping our customers meet the data subject rights requirements of GDPR. AdSpyder processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">California Residents (CCPA)</h3>
                <p className="mb-4">
                  The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.
                </p>
                <p className="mb-4">You may exercise the following rights:</p>
                <ul className="list-disc list-inside mb-4 space-y-2">
                  <li><strong>Right to Know and Access:</strong> You may submit a verifiable request for information regarding the categories of Personal Information we collect, use, or share; purposes for which categories of Personal Information are collected or used by us; categories of sources from which we collect Personal Information; and specific pieces of Personal Information we have collected about you.</li>
                  <li><strong>Right to Equal Service:</strong> We will not discriminate against you if you exercise your privacy rights.</li>
                  <li><strong>Right to Delete:</strong> You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</li>
                  <li><strong>Right to Opt-Out:</strong> Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
                </ul>
                <p className="mb-4">
                  If you make a request, we have one month to respond to you. We do not sell the Personal Information of our users.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">California Online Privacy Protection Act (CalOPPA)</h3>
                <p className="mb-4">
                  CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.
                </p>
                <p className="mb-4">CalOPPA users have the same rights as listed under CCPA above.</p>
              </section>

              {/* Data Sharing and Third Parties */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Data Sharing and Third Parties</h2>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Data Sharing with Third-Party Tools</h3>
                <p className="mb-4">
                  In our ongoing commitment to maintain transparency and protect your privacy, we wish to inform you about our practices regarding data sharing with third-party tools, including AI models. Our application may share limited and specific data with selected third-party tools to enhance your user experience, provide personalized content, and improve our services. This data may include, but is not limited to, user preferences, interaction metrics, and anonymized usage statistics.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Third-Party Services</h3>
                <p className="mb-4">
                  We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services").
                </p>
                <p className="mb-4">
                  You acknowledge and agree that AdSpyder shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. AdSpyder does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Links to Other Websites</h3>
                <p className="mb-4">
                  This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by AdSpyder. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Sale of Business</h3>
                <p className="mb-4">
                  We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of AdSpyder or any of its Corporate Affiliates, or that portion of AdSpyder or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Affiliates</h3>
                <p className="mb-4">
                  We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with AdSpyder, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Advertising</h3>
                <p className="mb-4">
                  This website may contain third party advertisements and links to third party sites. AdSpyder does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties.
                </p>
                <p className="mb-4">
                  Advertising keeps AdSpyder and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Remarketing Services</h3>
                <p className="mb-4">
                  We use remarketing services. In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're "following" people around the internet by serving ads on the websites and platforms they use most.
                </p>
                
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Payment Details</h3>
                <p className="mb-4">
                  In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.
                </p>
              </section>

              {/* Children's Privacy */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Children's Privacy</h2>
                <p className="mb-4">
                  We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                </p>
              </section>

              {/* Changes to This Policy */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Changes to This Policy</h2>
                <p className="mb-4">
                  We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.
                </p>
              </section>

              {/* Governing Law */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Governing Law</h2>
                <p className="mb-4">
                  This Privacy Policy is governed by the laws of India without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.
                </p>
                <p className="mb-4">
                  The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.
                </p>
              </section>

              {/* Contact Us */}
              <section className="mb-12">
                <h2 className="text-3xl font-bold text-gray-900 mb-6">Contact Us</h2>
                <p className="mb-6">
                  Don't hesitate to contact us if you have any questions about this Privacy Policy.
                </p>
                <div className="bg-gray-50 p-6 rounded-lg space-y-3">
                  <div>
                    <strong>Via Email:</strong> <a href="mailto:sales@adspyder.io" className="text-orange-600 hover:text-orange-700">sales@adspyder.io</a>
                  </div>
                  <div>
                    <strong>Via Phone:</strong> <a href="tel:+918792375409" className="text-orange-600 hover:text-orange-700">(+91) 8792375409</a>
                  </div>
                  <div>
                    <strong>Via Contact Form:</strong> <a href="https://adspyder.io/contact/" className="text-orange-600 hover:text-orange-700">https://adspyder.io/contact/</a>
                  </div>
                  <div>
                    <strong>Via Address:</strong><br />
                    810, 4th FLOOR, 27th MAIN, 1ST SECTOR, HSR LAYOUT<br />
                    Bengaluru, Bengaluru Urban, Karnataka, 560102<br />
                    India
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
